name: Run Build Tests
on:
  push:
  workflow_dispatch:

jobs:
  build_tests:
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev libfann-dev portaudio19-dev libpulse-dev
      - name: Build Source Packages
        run: |
          python setup.py sdist
      - name: Build Distribution Packages
        run: |
          python setup.py bdist_wheel
      - name: Install package
        run: |
          pip install .
