name: Run Unit Tests
on:
  pull_request: {}
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install pytest
          pip install .
      - name: Run tests
        run: pytest
